In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("hepatitis.csv")

In [3]:
data.columns=["class","age","sex","steroid", "ANTIVIRALS", "FATIGUE","MALAISE","ANOREXIA","LIVER_big","Liver_firm", "SPLEEN","SPIDERS","ASCITES","VARICES","BILIRUBIN","PHOSPHATE","SGOT","ALBUMIN","PROTIME","HISTOLOGY"]
data.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,SPLEEN,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
2,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1

In [4]:
#subset
female =data[data["sex"]==2]
male=data[data["sex"]==1]

In [5]:
female.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,SPLEEN,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
19,2,22,2,2,1,1,2,2,2,2,2,2,2,2,0.90,48,20,4.2,64,1
23,2,25,2,1,1,2,2,2,2,2,2,2,2,2,0.40,45,18,4.3,70,1
26,2,58,2,2,2,1,2,2,2,1,2,1,2,2,1.40,175,55,2.7,36,1
31,2,41,2,2,1,1,1,1,2,2,2,2,2,2,0.70,81,53,5.0,74,1
32,2,26,2,1,2,2,2,2,2,1,2,2,2,2,0.50,135,29,3.8,60,1

In [6]:
#(b)merge subset
merged_data = pd.concat([male,female])
merged_data.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,SPLEEN,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
0,2,50,1,1,2,1,2,2,1,2,2,2,2,2,0.90,135,42,3.5,?,1
1,2,78,1,2,2,1,2,2,2,2,2,2,2,2,0.70,96,32,4.0,?,1
2,2,31,1,?,1,2,2,2,2,2,2,2,2,2,0.70,46,52,4.0,80,1
3,2,34,1,2,2,2,2,2,2,2,2,2,2,2,1.00,?,200,4.0,?,1
4,2,34,1,2,2,2,2,2,2,2,2,2,2,2,0.90,95,28,4.0,75,1

In [7]:
sorted_data = data.sort_values(
    by=['age','SGOT','PROTIME'], 
    ascending=[True,False,True]
)

In [8]:
sorted_data.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,SPLEEN,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY
109,2,7,1,2,2,2,2,2,2,1,1,2,2,2,0.70,256,25,4.2,?,2
36,2,20,2,1,2,1,1,1,1,1,1,1,2,2,2.30,150,68,3.9,?,1
147,2,20,1,1,2,2,2,2,2,?,2,2,2,2,0.90,89,152,4.0,?,2
120,2,20,1,1,2,1,1,1,2,2,2,1,1,2,1.00,160,118,2.9,23,2
100,2,22,1,2,2,2,2,2,2,2,2,2,2,2,0.70,?,24,?,?,2

In [9]:
#transposed
transposed_data=sorted_data.transpose()
transposed_data.head()

,109,36,147,120,100,19,6,40,35,79,...,30,83,57,38,15,82,114,146,132,1
class,2,2,2,2,2,2,2,2,2,2,...,1,2,2,2,2,2,2,1,2,2
age,7,20,20,20,22,22,23,23,23,23,...,62,62,64,65,66,67,69,70,72,78
sex,1,2,1,1,1,2,1,1,1,1,...,1,2,1,1,1,2,2,1,1,1
steroid,2,1,1,1,2,2,2,2,2,2,...,1,2,2,2,2,1,2,1,2,2
ANTIVIRALS,2,2,2,2,2,1,2,2,2,2,...,2,2,1,2,2,2,2,2,1,2

In [10]:
#long form conversion
data["id"]=data.index
data.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,...,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,id
0,2,50,1,1,2,1,2,2,1,2,...,2,2,2,0.90,135,42,3.5,?,1,0
1,2,78,1,2,2,1,2,2,2,2,...,2,2,2,0.70,96,32,4.0,?,1,1
2,2,31,1,?,1,2,2,2,2,2,...,2,2,2,0.70,46,52,4.0,80,1,2
3,2,34,1,2,2,2,2,2,2,2,...,2,2,2,1.00,?,200,4.0,?,1,3
4,2,34,1,2,2,2,2,2,2,2,...,2,2,2,0.90,95,28,4.0,75,1,4

In [11]:
longform = pd.melt(data, id_vars=["id","age","class","sex"])
longform.head()

   id  age  class  sex variable value
0   0   50      2    1  steroid     1
1   1   78      2    1  steroid     2
2   2   31      2    1  steroid     ?
3   3   34      2    1  steroid     2
4   4   34      2    1  steroid     2

In [12]:
wideform= longform.pivot(index=["id","age","class","sex"], columns="variable", values="value")
wideform.head()

,,,variable,ALBUMIN,ANOREXIA,ANTIVIRALS,ASCITES,BILIRUBIN,FATIGUE,HISTOLOGY,LIVER_big,Liver_firm,MALAISE,PHOSPHATE,PROTIME,SGOT,SPIDERS,SPLEEN,VARICES,steroid
id,age,class,sex,,,,,,,,,,,,,,,,,
0,50,2,1,3.5,2,2,2,0.90,1,1,1,2,2,135,?,42,2,2,2,1
1,78,2,1,4.0,2,2,2,0.70,1,1,2,2,2,96,?,32,2,2,2,2
2,31,2,1,4.0,2,1,2,0.70,2,1,2,2,2,46,80,52,2,2,2,?
3,34,2,1,4.0,2,2,2,1.00,2,1,2,2,2,?,?,200,2,2,2,2
4,34,2,1,4.0,2,2,2,0.90,2,1,2,2,2,95,75,28,2,2,2,2

In [13]:
#data cleaning
print(data.isnull().sum())

class         0
age           0
sex           0
steroid       0
ANTIVIRALS    0
FATIGUE       0
MALAISE       0
ANOREXIA      0
LIVER_big     0
Liver_firm    0
SPLEEN        0
SPIDERS       0
ASCITES       0
VARICES       0
BILIRUBIN     0
PHOSPHATE     0
SGOT          0
ALBUMIN       0
PROTIME       0
HISTOLOGY     0
id            0
dtype: int64

In [14]:
data.replace("?",np.nan,inplace=True)
data.head()

,class,age,sex,steroid,ANTIVIRALS,FATIGUE,MALAISE,ANOREXIA,LIVER_big,Liver_firm,...,SPIDERS,ASCITES,VARICES,BILIRUBIN,PHOSPHATE,SGOT,ALBUMIN,PROTIME,HISTOLOGY,id
0,2,50,1,1,2,1,2,2,1,2,...,2,2,2,0.90,135,42,3.5,NaN,1,0
1,2,78,1,2,2,1,2,2,2,2,...,2,2,2,0.70,96,32,4.0,NaN,1,1
2,2,31,1,NaN,1,2,2,2,2,2,...,2,2,2,0.70,46,52,4.0,80,1,2
3,2,34,1,2,2,2,2,2,2,2,...,2,2,2,1.00,NaN,200,4.0,NaN,1,3
4,2,34,1,2,2,2,2,2,2,2,...,2,2,2,0.90,95,28,4.0,75,1,4

In [15]:
data.dropna(inplace=True)

In [16]:
for col in data:
    data[col]= pd.to_numeric(data[col])

In [17]:
data = data[(data[col]>=0).all(axis=1)]

ValueError: No axis named 1 for object type Series

In [58]:
print(data)

     class  age  sex steroid  ANTIVIRALS FATIGUE MALAISE ANOREXIA LIVER_big  \
4        2   34    1       2           2       2       2        2         2
9        2   39    1       1           1       2       2        2         1
10       2   32    1       2           1       1       2        2         2
11       2   41    1       2           1       1       2        2         2
12       2   30    1       2           2       1       2        2         2
..     ...  ...  ...     ...         ...     ...     ...      ...       ...
138      2   45    1       2           1       2       2        2         2
142      1   49    1       1           2       1       1        2         2
144      2   31    1       1           2       1       2        2         2
152      2   53    2       1           2       1       2        2         2
153      1   43    1       2           2       1       2        2         2

    Liver_firm  ... SPIDERS ASCITES VARICES BILIRUBIN PHOSPHATE SGOT ALBUMIN  \
4            2  ...       2       2       2      0.90        95   28     4.0
9            1  ...       2       2       2      1.30        78   30     4.4
10           1  ...       1       2       2      1.00        59  249     3.7
11           1  ...       2       2       2      0.90        81   60     3.9
12           1  ...       2       2       2      2.20        57  144     4.9
..         ...  ...     ...     ...     ...       ...       ...  ...     ...
138          2  ...       2       2       2      1.30        85   44     4.2
142          2  ...       1       2       2      1.40        85   70     3.5
144          2  ...       2       2       2      1.20        75  173     4.2
152          2  ...       1       2       1      1.50        81   19     4.1
153          2  ...       1       1       2      1.20       100   19     3.1

    PROTIME HISTOLOGY   id
4        75         1    4
9        85         1    9
10       54         1   10
11       52         1   11
12       78         1   12
..      ...       ...  ...
138      85         2  138
142      35         2  142
144      54         2  144
152      48         2  152
153      42         2  153

[80 rows x 21 columns]

In [69]:
#outlier
numeric_data = data.select_dtypes(include='number')

Q1 = numeric_data.quantile(0.25)
Q3= numeric_data.quantile(0.75)

IQR= Q3-Q1

lower = Q1 - 1.5*IQR
higher= Q3+1.5*IQR

data_clean =numeric_data[
       ((numeric_data>=lower)& (numeric_data<=higher)).all(axis=1) ]
print (data_clean)

     class  age  sex  ANTIVIRALS  HISTOLOGY   id
4        2   34    1           2          1    4
9        2   39    1           1          1    9
10       2   32    1           1          1   10
11       2   41    1           1          1   11
12       2   30    1           2          1   12
14       2   38    1           2          1   14
16       2   40    1           2          1   16
17       2   38    1           2          2   17
18       2   38    1           1          1   18
20       2   27    1           2          1   20
21       2   31    1           2          1   21
22       2   42    1           2          1   22
24       2   27    1           2          1   24
27       2   61    1           2          1   27
28       2   51    1           1          1   28
33       2   35    1           2          1   33
35       2   23    1           2          1   35
37       2   42    1           2          1   37
38       2   65    1           2          2   38
39       2   52    1           1          1   39
41       2   33    1           2          1   41
42       2   56    1           2          1   42
47       2   36    1           2          1   47
48       2   38    1           1          1   48
51       2   44    1           2          1   51
52       2   40    1           1          1   52
53       2   30    1           2          1   53
56       2   30    1           1          1   56
57       2   64    1           1          1   57
59       2   37    1           2          1   59
60       2   32    1           2          1   60
61       2   32    1           2          1   61
62       2   36    1           2          1   62
63       2   49    1           2          1   63
67       2   39    1           2          1   67
74       2   32    1           1          1   74
77       2   34    1           2          1   77
80       2   36    1           2          1   80
81       2   30    1           2          1   81
84       2   28    1           2          1   84
88       2   38    1           2          2   88
94       2   40    1           1          2   94
95       2   30    1           2          2   95
101      2   27    1           2          2  101
102      2   51    1           2          2  102
107      2   54    1           1          2  107
116      2   50    1           2          2  116
120      2   20    1           2          2  120
123      2   50    1           2          2  123
127      2   54    1           2          2  127
129      2   54    1           2          2  129
132      2   72    1           1          2  132
134      2   25    1           2          2  134
136      2   38    1           2          2  136
138      2   45    1           1          2  138
144      2   31    1           2          2  144

In [75]:
#stransformation
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X= data.drop("class",axis=1)
y=data["class"]

In [76]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [78]:
#regress
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X_scaled,y, test_size=0.2, random_state=42)

In [81]:
lr_model= LogisticRegression()
lr_model.fit(X_train,y_train)
y_pred_lr=lr_model.predict(X_test)
print("accuracy score: ", accuracy_score(y_test,y_pred_lr))

accuracy score:  0.875