In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

In [3]:
data = pd.read_csv("BreastCancerWc.csv")

In [7]:
data.head()

,Sample_code,clump-thick,uniform_size,uniform_shape,marg_adhesion,ephithelial,nuclei,Chromatin,normal_ Nucleoli,mitoseis,type_cancer
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4

In [8]:
data.columns=["Sample_code ","clump-thick","uniform_size","uniform_shape","marg_adhesion","ephithelial","nuclei","Chromatin","normal_ Nucleoli","mitoseis","type_cancer"]

In [9]:
data.head()

,Sample_code,clump-thick,uniform_size,uniform_shape,marg_adhesion,ephithelial,nuclei,Chromatin,normal_ Nucleoli,mitoseis,type_cancer
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4

In [10]:
data.replace("?",np.nan,inplace=True)

,Sample_code,clump-thick,uniform_size,uniform_shape,marg_adhesion,ephithelial,nuclei,Chromatin,normal_ Nucleoli,mitoseis,type_cancer
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [11]:
data.dropna()

,Sample_code,clump-thick,uniform_size,uniform_shape,marg_adhesion,ephithelial,nuclei,Chromatin,normal_ Nucleoli,mitoseis,type_cancer
0,1002945,5,4,4,5,7,10,3,2,1,2
1,1015425,3,1,1,1,2,2,3,1,1,2
2,1016277,6,8,8,1,3,4,3,7,1,2
3,1017023,4,1,1,3,2,1,3,1,1,2
4,1017122,8,10,10,8,7,10,9,7,1,4
...,...,...,...,...,...,...,...,...,...,...,...
693,776715,3,1,1,1,3,2,1,1,1,2
694,841769,2,1,1,1,2,1,1,1,1,2
695,888820,5,10,10,3,7,3,8,10,2,4
696,897471,4,8,6,4,3,4,10,6,1,4
697,897471,4,8,8,5,4,5,10,4,1,4

In [12]:
for col in data.columns:
    data[col]=pd.to_numeric(data[col],errors="coerce")

In [ ]:
data =da