In [5]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv("adult.csv")
data.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [12]:
data.columns=["age","workclass","fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-l","capital-g","hpw","native-country","income"]

In [13]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-l,capital-g,hpw,native-country,income
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [16]:
US=data[data["native-country"]=="United-States"]
cuba=data[data["native-country"]=="Cuba"]

In [17]:
merged_data=pd.concat([US,cuba])

In [20]:
sorted_data=data.sort_values(
    by=["age","hpw"],
    ascending=[True,True])

In [21]:
sorted_data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-l,capital-g,hpw,native-country,income
9820,17,Self-emp-inc,143034,10th,6,Never-married,Other-service,Own-child,White,Male,0,0,4,United-States,<=50K
22927,17,?,332666,10th,6,Never-married,?,Own-child,White,Female,0,0,4,United-States,<=50K
448,17,?,258872,11th,7,Never-married,?,Own-child,White,Female,0,0,5,United-States,<=50K
1388,17,Private,46496,11th,7,Never-married,Other-service,Own-child,White,Male,0,0,5,United-States,<=50K
13811,17,Private,195505,10th,6,Never-married,Sales,Own-child,White,Male,0,0,5,United-States,<=50K

In [23]:
transposed_data = sorted_data.transpose()

In [24]:
data["id"]=data.index
long_form = pd.melt(data, id_vars=["id","age"])

In [25]:
print(long_form)

           id  age   variable              value
0           0   50  workclass   Self-emp-not-inc
1           1   38  workclass            Private
2           2   53  workclass            Private
3           3   28  workclass            Private
4           4   37  workclass            Private
...       ...  ...        ...                ...
455835  32555   27     income              <=50K
455836  32556   40     income               >50K
455837  32557   58     income              <=50K
455838  32558   22     income              <=50K
455839  32559   52     income               >50K

[455840 rows x 4 columns]

In [26]:
wide_form= long_form.pivot(index=["id","age"],columns="variable",values="value")

In [27]:
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-l,capital-g,hpw,native-country,income,id
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,1
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,2
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,3
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,4

In [28]:
print(data.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-l         0
capital-g         0
hpw               0
native-country    0
income            0
id                0
dtype: int64

In [29]:
data.replace("?",np.nan,inplace=True)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-l,capital-g,hpw,native-country,income,id
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,1
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,2
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,3
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,32555
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,32556
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,32557
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,32558
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,32559

In [30]:
numeric_data = data.select_dtypes(include='number')
print(numeric_data)

       age  fnlwgt  education-num  capital-l  capital-g  hpw     id
0       50   83311             13          0          0   13      0
1       38  215646              9          0          0   40      1
2       53  234721              7          0          0   40      2
3       28  338409             13          0          0   40      3
4       37  284582             14          0          0   40      4
...    ...     ...            ...        ...        ...  ...    ...
32555   27  257302             12          0          0   38  32555
32556   40  154374              9          0          0   40  32556
32557   58  151910              9          0          0   40  32557
32558   22  201490              9          0          0   20  32558
32559   52  287927              9      15024          0   40  32559

[32560 rows x 7 columns]

In [31]:
data=data[(numeric_data>=0).all(axis=1)]

In [32]:
data.dropna()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-l,capital-g,hpw,native-country,income,id
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,0
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,1
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,2
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,3
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K,32555
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K,32556
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K,32557
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K,32558
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K,32559

In [35]:
#outliers

Q1=numeric_data.quantile(0.25) 
Q3=numeric_data.quantile(0.75)

IQR= Q3-Q1

lower= Q1-1.5*IQR
higher=Q3+1.5*IQR

data_clean= data[~((numeric_data<lower) | (numeric_data>higher)).all(axis=1)]

In [36]:
print(data_clean)

       age          workclass  fnlwgt    education  education-num  \
0       50   Self-emp-not-inc   83311    Bachelors             13
1       38            Private  215646      HS-grad              9
2       53            Private  234721         11th              7
3       28            Private  338409    Bachelors             13
4       37            Private  284582      Masters             14
...    ...                ...     ...          ...            ...
32555   27            Private  257302   Assoc-acdm             12
32556   40            Private  154374      HS-grad              9
32557   58            Private  151910      HS-grad              9
32558   22            Private  201490      HS-grad              9
32559   52       Self-emp-inc  287927      HS-grad              9

            marital-status          occupation    relationship    race  \
0       Married-civ-spouse     Exec-managerial         Husband   White
1                 Divorced   Handlers-cleaners   Not-in-family   White
2       Married-civ-spouse   Handlers-cleaners         Husband   Black
3       Married-civ-spouse      Prof-specialty            Wife   Black
4       Married-civ-spouse     Exec-managerial            Wife   White
...                    ...                 ...             ...     ...
32555   Married-civ-spouse        Tech-support            Wife   White
32556   Married-civ-spouse   Machine-op-inspct         Husband   White
32557              Widowed        Adm-clerical       Unmarried   White
32558        Never-married        Adm-clerical       Own-child   White
32559   Married-civ-spouse     Exec-managerial            Wife   White

           sex  capital-l  capital-g  hpw  native-country  income     id
0         Male          0          0   13   United-States   <=50K      0
1         Male          0          0   40   United-States   <=50K      1
2         Male          0          0   40   United-States   <=50K      2
3       Female          0          0   40            Cuba   <=50K      3
4       Female          0          0   40   United-States   <=50K      4
...        ...        ...        ...  ...             ...     ...    ...
32555   Female          0          0   38   United-States   <=50K  32555
32556     Male          0          0   40   United-States    >50K  32556
32557   Female          0          0   40   United-States   <=50K  32557
32558     Male          0          0   20   United-States   <=50K  32558
32559   Female      15024          0   40   United-States    >50K  32559

[32560 rows x 16 columns]

In [80]:
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [82]:
X= data_clean.drop("income",axis=1)
y=data_clean["income"]

In [83]:
from sklearn.preprocessing import LabelEncoder

In [101]:
le = LabelEncoder()

for col in data_clean.columns:
    if data_clean[col].dtype=="object" or str(data_clean[col].dtype)=="str":
        data_clean[col]=le.fit_transform(data_clean[col])

In [90]:
X= data_clean.drop("income",axis=1)
y=data_clean["income"]

In [91]:
scaler= StandardScaler()

In [92]:
X_scaled = scaler.fit_transform(X)

In [93]:
print(X.dtypes)

age               int64
workclass         int64
fnlwgt            int64
education         int64
education-num     int64
marital-status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital-l         int64
capital-g         int64
hpw               int64
native-country    int64
id                int64
dtype: object

In [94]:
X_train,X_test,y_train,y_test = train_test_split(X_scaled,y,test_size=0.2,random_state=42)

In [96]:
lr_model =LogisticRegression()
lr_model.fit(X_train,y_train)
y_pred_lr= lr_model.predict(X_test)
print("accuracy score of regression:", accuracy_score(y_test,y_pred_lr))

accuracy score of regression: 0.8206388206388207